### ISSUE TITLE
Many errors in this repo

### ISSUE THREAD

**Issue by BillMatrix** [google-research/clevr_robot_env#2]
I encountered many issues when using this repo:
- there's no 'point_mass' "body" in the given model:
Here's the error: 
```
Traceback (most recent call last):
  File "/Users/billzhu/.conda/envs/rep_learning/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-d7bebc982a78>", line 1, in <module>
    env.get_body_com('point_mass')
  File "/Users/billzhu/.conda/envs/rep_learning/lib/python3.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 168, in get_body_com
    return self.data.get_body_xpos(body_name)
  File "mujoco_py/generated/wrappers.pxi", line 2604, in mujoco_py.cymj.PyMjData.get_body_xpos
  File "mujoco_py/generated/wrappers.pxi", line 1019, in mujoco_py.cymj.PyMjModel.body_name2id
ValueError: No "body" with name point_mass exists. Available "body" names = ('world', 'object1', 'object2', 'object3', 'object4', 'object5', 'r_wrist_flex_link', 'r_wrist_roll_link', 'tips_arm').
```
- The default XML you provide only has three objects, which causes error in the code.
- You did not define physics in the environment, where the camera uses. Also the camera_setup function does not exist on line 274 of env.py
- The mujoco environment you use I think is the deepmind's control environment (dm_control.mujoco), whose physics' qpos and qvel does not match openai gym's mujoco_env's qpos and qvel, which causes errors when taking any actions
- I don't know which mujoco_env you are using, but mujoco_env does not have the following two arguments:
```
max_episode_steps=maximum_episode_steps,
reward_threshold=0.,
```

**Comment by yidingjiang** [comment]
Hi Bill,
You are right the mujoco env that I am using is a wrapper around deepmind control environment. I am working on a fix and hope to patch the code this week.

**Comment by yidingjiang** [comment]
All these issues should be fixed now. Can you pull the latest code and confirm this?

**Comment by BillMatrix** [comment]
Thanks! I'll take a look tonight!
