### ISSUE TITLE
A error occurred when I run example.py

### ISSUE THREAD

**Issue by xiaohythu** [google-research/clevr_robot_env#4]
When I run the example.py with "python example.py", the following error occurred:

Traceback (most recent call last):
  File "example.py", line 25, in <module>
    from env import ClevrEnv
  File "/home/rll/xiaohouyuan/clevr_robot_env/env.py", line 40, in <module>
    import mujoco_env as mujoco_env  # custom mujoco_env
  File "/home/rll/xiaohouyuan/clevr_robot_env/mujoco_env.py", line 24, in <module>
    from dm_control import mujoco
  File "/home/rll/anaconda3/envs/py36/lib/python3.6/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
    from dm_control.mujoco.engine import action_spec
  File "/home/rll/anaconda3/envs/py36/lib/python3.6/site-packages/dm_control/mujoco/engine.py", line 44, in <module>
    from dm_control import _render
  File "/home/rll/anaconda3/envs/py36/lib/python3.6/site-packages/dm_control/_render/__init__.py", line 75, in <module>
    Renderer = import_func()
  File "/home/rll/anaconda3/envs/py36/lib/python3.6/site-packages/dm_control/_render/__init__.py", line 36, in _import_egl
    from dm_control._render.pyopengl.egl_renderer import EGLContext
  File "/home/rll/anaconda3/envs/py36/lib/python3.6/site-packages/dm_control/_render/pyopengl/egl_renderer.py", line 66, in <module>
    EGL_DISPLAY = create_initialized_headless_egl_display()
  File "/home/rll/anaconda3/envs/py36/lib/python3.6/site-packages/dm_control/_render/pyopengl/egl_renderer.py", line 49, in create_initialized_headless_egl_display
    for device in EGL.eglQueryDevicesEXT():
  File "/home/rll/anaconda3/envs/py36/lib/python3.6/site-packages/dm_control/_render/pyopengl/egl_ext.py", line 65, in eglQueryDevicesEXT
    success = _eglQueryDevicesEXT(max_devices, devices, num_devices)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_c_void_p instance instead of EGLDeviceEXT_pointer_Array_10

Any instructions?

**Comment by dylanturpin** [comment]
Hello @xiaohythu , were you able to resolve the error message?

**Comment by xiaohythu** [comment]
Acctually， I solved this problem. You have to reinstall the dmcontrol

**Comment by ajabri** [comment]
@xiaohythu How did you reinstall dmcontrol? With `pip install dm-control`? I am having the ArgumentError issue you mention above.
